# Generated by Django 2.1.5 on 2022-04-07 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('photo', models.CharField(default='-', max_length=20)),
                ('minBidPrice', models.IntegerField(default=0)),
                ('stating_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(blank=True)),
                ('url', models.CharField(default='-', max_length=30)),
                ('timezone', models.CharField(default='<function get_current_timezone_name at 0x000001ED7FE9B0D0>', max_length=30)),
                ('category', models.CharField(default='-', max_length=30)),
            ],
        ),
    ]
