# Generated by Django 2.1.5 on 2022-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20220408_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='timezone',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
