# Generated by Django 2.1.5 on 2022-04-08 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0004_auctionitem_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('bid_time', models.DateTimeField(default=datetime.datetime.now)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='bids',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.Bid'),
            preserve_default=False,
        ),
    ]
