# Generated by Django 2.1.5 on 2022-04-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20220408_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='views',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
