# Generated by Django 2.1.5 on 2022-04-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auctionitem_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='auctionitem',
            old_name='stating_time',
            new_name='start_date',
        ),
    ]
