# Generated by Django 2.1.5 on 2022-04-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20220408_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='auctionitem',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='url',
        ),
    ]
