# Generated by Django 2.1.5 on 2022-04-09 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20220409_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(blank=None, default=datetime.date.today, null=None),
        ),
    ]
