# Generated by Django 2.1.5 on 2022-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20220409_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='startDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
