# Generated by Django 2.1.5 on 2022-04-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_auto_20220410_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
