# Generated by Django 2.1.5 on 2022-04-09 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0014_auto_20220410_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Bid'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='views',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
